### ISSUE TITLE
Question: is this OCI distribution compliant?

### ISSUE THREAD

**Issue by jdolitsky** [NicolasT/static-container-registry#10]
Does this registry comply with OCI?
https://github.com/opencontainers/distribution-spec/blob/master/spec.md

**Comment by NicolasT** [comment]
No, it's based on the Docker distribution spec, not the OCI one. I believe it should be possible to rework this tool to serve an OCI distribution-spec compliant 'registry', but didn't implement this. PR would likely  be accepted, though.
